version: "3.8"
services:
    deepstream:
        image: deepstream-test
        container_name: deepstream
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - ./:/app/
          - /tmp/.X11-unix:/tmp/.X11-unix
        working_dir: /app/
        environment:
          - DISPLAY=${DISPLAY}
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: [ '0' ]
                          capabilities: [ gpu ]
        command: "tail -f /dev/null"
